spring.application.name=traveltime
server.port=8081

spring.app.jwt-secret=ZWIujtJ7qzAQYiDLUH9MHDnE0smTRH8htDfE9EWS5Bo
spring.app.jwt-expiration-ms=86400000

spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/traveltimedb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.default_batch_fetch_size=100

logging.config=classpath:log4j2.xml